version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - aws --version
      - mvn clean package -DskipTests
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=024988467957.dkr.ecr.ap-south-1.amazonaws.com/simply-cinema
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 339713037827.dkr.ecr.ap-south-1.amazonaws.com
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      # IMPORTANT: container name must match ECS Task Definition container name
      - DOCKER_CONTAINER_NAME=simply-cinema
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
